# Generated by Django 3.2.4 on 2021-06-26 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0003_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200, verbose_name='Car Name')),
                ('model_number', models.CharField(max_length=200, verbose_name='Model Number')),
                ('price', models.FloatField(verbose_name='Price In KM')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='vehicle_image', verbose_name='Vehicle Image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.vehicletype', verbose_name='Vehicle Type')),
            ],
        ),
    ]
