# Generated by Django 3.2.4 on 2021-09-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owner', '0002_vehicle_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_name',
            field=models.CharField(max_length=200, verbose_name='Vehicle Name'),
        ),
    ]
