# Generated by Django 3.2.4 on 2021-06-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0003_distance'),
        ('car_owner', '0002_vehicle_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=10, verbose_name='Total Price ')),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.from', verbose_name='From ')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.to', verbose_name='To ')),
                ('vehicle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_owner.vehicle')),
            ],
        ),
    ]
