# Generated by Django 3.2.4 on 2021-07-02 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 14, 36, 36, 255311, tzinfo=utc), verbose_name='Reservation Date'),
            preserve_default=False,
        ),
    ]
