# Generated by Django 3.2.4 on 2021-06-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_from_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=5, verbose_name='Distance in KM')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.from')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.to')),
            ],
        ),
    ]
